### ISSUE TITLE
Why not just check to see that the function is attached to the prototype?

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/js-object-oriented-prototypes-lab#3]
In the tests to look for the function being on the prototype you check that two instances functions are equal. Thoughts on doing this vs. just looking for `person.prototype.helloWorld` exists?

**Comment by JeffKatzy** [comment]
Yea, the point was to show what a protoype gives you - that it makes the functions the same.

**Comment by jmburges** [comment]
kk makes sense
